const data = {
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInstock: 20,
      description: 'A popular shirt , very good for man',
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      category: 'Shirts',
      image: '/images/shirt2.jpg',
      price: 80,
      brand: 'Adidas',
      rating: 3.1,
      numReviews: 10,
      countInstock: 20,
      description: 'A popular shirt , very good for man',
    },
    {
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shirts',
      image: '/images/shirt3.jpg',
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 3,
      countInstock: 20,
      description: 'A popular shirt , very good for man',
    },
    {
      name: 'Golf Pants',
      slug: 'golf-pants',
      category: 'Pants',
      image: '/images/pants1.jpg',
      price: 70,
      brand: 'Oliver',
      rating: 4.5,
      numReviews: 8,
      countInstock: 20,
      description: 'A popular pants , very good for man',
    },
    {
      name: 'Fit Pants',
      slug: 'fit-pants',
      category: 'Pants',
      image: '/images/pants2.jpg',
      price: 70,
      brand: 'Zara',
      rating: 4.5,
      numReviews: 8,
      countInstock: 20,
      description: 'A popular pants , very good for man',
    },
    {
      name: 'Classic Pants',
      slug: 'classic-pants',
      category: 'Pants',
      image: '/images/pants3.jpg',
      price: 70,
      brand: 'Casely',
      rating: 4.5,
      numReviews: 8,
      countInstock: 20,
      description: 'A popular pants , very good for man',
    },
  ],
};

export default data;
